# -*- coding: utf-8 -*-
"""perfumes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYr4D1Xk_G4uKYIkHNHgNPKo8McJV6kr
"""

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the files you'd like to load
file_path_men = "ebay_mens_perfume.csv"
file_path_women = "ebay_womens_perfume.csv"

# Load the men's perfume dataset
print(f"Loading {file_path_men}...")
df_men = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "kanchana1990/perfume-e-commerce-dataset-2024",
  file_path_men
)

print("First 5 records of Men's Perfume Data:")
print(df_men.head())

print(f"\nLoading {file_path_women}...")
# Load the women's perfume dataset
df_women = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "kanchana1990/perfume-e-commerce-dataset-2024",
  file_path_women
)

print("First 5 records of Women's Perfume Data:")
print(df_women.head())